site_name: MALLARDO MICHELE
site_url: https://mydomain.org/mysite
theme:
  name: material
  theme:
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.path
    - navigation.top

nav:
  - Home: index.md
  - About: 
    - About Me: about/about.md
    - Bio: about/Bio.md